In [1]:
import pandas as pd
import numpy as np
import pyarrow.parquet as pq

In [18]:
df = pd.read_csv('/Users/kdugg/Documents/zillow-short.csv')

In [19]:
df = df.rename(columns = {'Unnamed: 0':'ZIP_CODE_SHORT'})

In [20]:
df['ZIP_CODE_SHORT'] = df['ZIP_CODE_SHORT'].apply(lambda x: str(x).zfill(3))
df

,ZIP_CODE_SHORT,1/31/1996,2/29/1996,3/31/1996,4/30/1996,5/31/1996,6/30/1996,7/31/1996,8/31/1996,9/30/1996,...,8/31/2019,9/30/2019,10/31/2019,11/30/2019,12/31/2019,1/31/2020,2/29/2020,3/31/2020,4/30/2020,5/31/2020
0,100,231064.0,229625.0,229702.0,229677.0,230203.0,230842.0,230729.0,231538.0,231890.0,...,1255626,1239473,1225833,1221555,1217736,1198491,1172006,1138563,1120424,1103971
1,606,211597.0,211439.0,211029.0,210893.0,210326.0,210511.0,210297.0,210907.0,211801.0,...,495147,494290,493336,492329,491487,491249,492211,493494,494102,493717
2,100,236643.0,236693.0,236824.0,237667.0,238894.0,239898.0,240232.0,240332.0,240710.0,...,1128603,1114223,1105521,1108518,1127397,1146829,1160419,1161442,1171805,1178287
3,774,200691.0,200938.0,200741.0,199551.0,198412.0,197745.0,198508.0,198196.0,197542.0,...,336294,336438,336472,336463,336577,336340,336589,337122,338281,339317
4,606,287425.0,287162.0,286633.0,286488.0,285798.0,285888.0,285385.0,285956.0,287057.0,...,649878,648659,647684,646281,644917,644493,644516,644757,643758,642694
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30473,014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,383799,384163,387222,391462,397202,399491,400217,399847,399536,398968
30474,008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,166198,166607,167033,167465,167210,167398,168285,168711,168552,167462
30475,008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,58919,59169,59411,59645,59870,60085,60249,60460,60682,60895
30476,008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,127016,127443,127610,127371,127186,127064,127558,127555,127264,126449
30477,008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,107926,108634,108856,108517,107556,107314,107488,107797,107923,107745

In [21]:
df = df[df['1/31/1996'].notna()]

In [22]:
df

,ZIP_CODE_SHORT,1/31/1996,2/29/1996,3/31/1996,4/30/1996,5/31/1996,6/30/1996,7/31/1996,8/31/1996,9/30/1996,...,8/31/2019,9/30/2019,10/31/2019,11/30/2019,12/31/2019,1/31/2020,2/29/2020,3/31/2020,4/30/2020,5/31/2020
0,100,231064.0,229625.0,229702.0,229677.0,230203.0,230842.0,230729.0,231538.0,231890.0,...,1255626,1239473,1225833,1221555,1217736,1198491,1172006,1138563,1120424,1103971
1,606,211597.0,211439.0,211029.0,210893.0,210326.0,210511.0,210297.0,210907.0,211801.0,...,495147,494290,493336,492329,491487,491249,492211,493494,494102,493717
2,100,236643.0,236693.0,236824.0,237667.0,238894.0,239898.0,240232.0,240332.0,240710.0,...,1128603,1114223,1105521,1108518,1127397,1146829,1160419,1161442,1171805,1178287
3,774,200691.0,200938.0,200741.0,199551.0,198412.0,197745.0,198508.0,198196.0,197542.0,...,336294,336438,336472,336463,336577,336340,336589,337122,338281,339317
4,606,287425.0,287162.0,286633.0,286488.0,285798.0,285888.0,285385.0,285956.0,287057.0,...,649878,648659,647684,646281,644917,644493,644516,644757,643758,642694
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30438,891,192887.0,192655.0,192684.0,192524.0,192504.0,192393.0,192484.0,192877.0,193393.0,...,374346,374397,375404,377406,379112,381290,382401,384819,386294,386969
30445,040,283242.0,285425.0,288717.0,293736.0,298577.0,301703.0,304147.0,306746.0,310558.0,...,823889,827785,836301,844565,850545,855614,859370,867493,873618,881948
30449,214,422111.0,423372.0,422374.0,422660.0,420812.0,419609.0,416157.0,412930.0,410505.0,...,964417,961737,964289,965774,965847,962111,957989,957427,955617,953298
30457,435,61898.0,61425.0,61010.0,60657.0,60297.0,60195.0,59746.0,59655.0,59328.0,...,87365,87295,86944,87047,87296,87486,87441,87282,87337,87028
30472,863,71492.0,70916.0,70830.0,70813.0,71404.0,71956.0,72205.0,72587.0,72949.0,...,163395,164165,163791,164460,164455,165170,164194,165414,166476,166865

In [23]:
df.groupby(['ZIP_CODE_SHORT']).mean()

,1/31/1996,2/29/1996,3/31/1996,4/30/1996,5/31/1996,6/30/1996,7/31/1996,8/31/1996,9/30/1996,10/31/1996,...,8/31/2019,9/30/2019,10/31/2019,11/30/2019,12/31/2019,1/31/2020,2/29/2020,3/31/2020,4/30/2020,5/31/2020
ZIP_CODE_SHORT,,,,,,,,,,,,,,,,,,,,,
010,127793.954545,127611.750000,127584.431818,127463.750000,127434.318182,127415.522727,127414.659091,127539.159091,127678.409091,127719.954545,...,264137.227273,264864.295455,265348.318182,266124.045455,267025.704545,268116.045455,269550.454545,270910.113636,272516.181818,273209.136364
011,95046.700000,95106.300000,95146.100000,95125.300000,95107.100000,94946.800000,94903.200000,94733.500000,94765.600000,94719.700000,...,193352.700000,194553.100000,195903.600000,197044.700000,197910.300000,198848.800000,200491.400000,201370.400000,202123.900000,202474.900000
012,152939.000000,152747.071429,152395.285714,151950.571429,151415.857143,150841.857143,150336.214286,150390.000000,150694.000000,150977.071429,...,294510.142857,293405.000000,293369.214286,293681.071429,294721.571429,294987.571429,295213.785714,295030.571429,295120.500000,294198.714286
013,96047.062500,96062.375000,96053.687500,96162.562500,96255.875000,96383.750000,96424.187500,96597.875000,96839.375000,97057.625000,...,227629.062500,227389.937500,227879.562500,227693.375000,227642.812500,227726.937500,229097.312500,230553.937500,232363.375000,234215.500000
014,133912.888889,134038.166667,134142.333333,134407.500000,134567.555556,134814.722222,135018.555556,135460.444444,135866.833333,136512.944444,...,314648.277778,315445.611111,316610.166667,317781.222222,318935.666667,320379.888889,321565.277778,323152.555556,324178.166667,324879.944444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,137231.869565,137332.608696,137476.130435,137951.956522,138177.565217,138155.869565,138067.391304,138298.217391,138690.608696,138715.695652,...,316876.260870,319383.217391,322211.478261,324224.260870,326168.130435,328677.086957,331518.913043,334951.043478,337602.565217,339418.086957
991,107608.888889,107434.555556,107499.555556,107576.000000,107896.000000,108114.555556,108238.222222,108363.777778,108598.777778,109049.000000,...,267167.666667,268049.555556,268884.666667,269042.111111,269157.555556,269325.555556,270367.888889,270735.555556,270903.000000,270816.444444
992,116967.285714,116964.714286,116851.214286,116844.714286,116786.500000,116693.785714,116535.785714,116480.000000,116574.428571,116646.642857,...,265400.214286,267652.500000,270400.500000,272511.642857,274580.000000,277243.214286,280485.857143,283940.785714,286385.285714,287699.785714
993,92142.666667,92349.111111,92553.111111,92975.444444,93314.888889,93500.111111,93571.444444,93719.888889,93804.666667,94025.777778,...,269432.444444,270656.777778,271746.000000,272502.666667,273578.555556,274422.333333,275060.777778,274878.111111,274339.111111,273924.000000
995,138147.153846,138781.615385,139392.230769,140611.538462,141582.153846,142481.846154,143311.923077,143863.230769,144154.000000,144124.000000,...,325667.846154,327367.307692,329046.076923,330782.769231,332152.461538,333308.307692,332136.923077,331055.000000,328089.384615,327958.769231

In [5]:
daycols = (pd.DatetimeIndex(df.columns[1:]) + pd.DateOffset(1)).tolist()

In [6]:
daycol = ["{}/{}/{}".format(str(x.month).zfill(2), "01", x.year) for x in daycols]

In [7]:
daycol.insert(0, "ZIP_CODE_SHORT")

In [8]:
df.columns = daycol

In [ ]:
df

In [ ]:
resetdf = df.reset_index()
del resetdf['index']

In [ ]:
resetdf

In [15]:
groupwithout = df.groupby(['ZIP_CODE_SHORT']).mean()

In [16]:
df.groupby('ZIP_CODE_SHORT').agg(lambda x: x.mean(skipna=False))

,02/01/1996,03/01/1996,04/01/1996,05/01/1996,06/01/1996,07/01/1996,08/01/1996,09/01/1996,10/01/1996,11/01/1996,...,09/01/2019,10/01/2019,11/01/2019,12/01/2019,01/01/2020,02/01/2020,03/01/2020,04/01/2020,05/01/2020,06/01/2020
ZIP_CODE_SHORT,,,,,,,,,,,,,,,,,,,,,
005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,78297.000000,78444.000000,79366.000000,80190.000000,81391.000000,82304.000000,83391.000000,84272.000000,85330.000000,86915.000000
006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,99728.428571,100061.928571,100422.785714,100817.571429,101092.071429,101319.214286,101336.000000,101379.857143,101462.714286,101763.071429
007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,174806.916667,175283.333333,175583.083333,175667.750000,175679.833333,175761.833333,175706.916667,175612.666667,175675.583333,176104.750000
008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,115014.750000,115463.250000,115727.500000,115749.500000,115455.500000,115465.250000,115895.000000,116130.750000,116105.250000,115637.750000
009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,219365.500000,217754.000000,216254.500000,213795.000000,211528.500000,209691.750000,208482.750000,207866.000000,208269.750000,208874.250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,307373.368421,309146.736842,310896.631579,312566.842105,313949.631579,315316.789474,314871.000000,314416.631579,312464.105263,312666.315789
996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,214382.086957,215086.608696,216002.782609,217058.434783,218245.652174,219458.565217,220541.869565,221012.913043,221505.565217,221803.347826
997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,239568.166667,240685.000000,241336.000000,240901.166667,240914.666667,240978.000000,241781.000000,242169.500000,241875.166667,241499.833333
998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,314637.400000,315506.200000,316727.000000,317920.600000,318928.400000,319667.800000,320106.600000,320357.200000,320494.800000,320604.600000
999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,261775.000000,263174.500000,264393.000000,265411.000000,266197.500000,266873.500000,267348.500000,267853.000000,268123.000000,268425.500000

In [24]:
thing = groupwithout[groupwithout['02/01/1996'].notna()]

In [27]:
thing.to_parquet('/Users/kdugg/Documents/zillow_data_grouped.parquet')

In [26]:
df.groupby(['ZIP_CODE_SHORT']).mean()

,1/31/1996,2/29/1996,3/31/1996,4/30/1996,5/31/1996,6/30/1996,7/31/1996,8/31/1996,9/30/1996,10/31/1996,...,8/31/2019,9/30/2019,10/31/2019,11/30/2019,12/31/2019,1/31/2020,2/29/2020,3/31/2020,4/30/2020,5/31/2020
ZIP_CODE_SHORT,,,,,,,,,,,,,,,,,,,,,
010,127793.954545,127611.750000,127584.431818,127463.750000,127434.318182,127415.522727,127414.659091,127539.159091,127678.409091,127719.954545,...,264137.227273,264864.295455,265348.318182,266124.045455,267025.704545,268116.045455,269550.454545,270910.113636,272516.181818,273209.136364
011,95046.700000,95106.300000,95146.100000,95125.300000,95107.100000,94946.800000,94903.200000,94733.500000,94765.600000,94719.700000,...,193352.700000,194553.100000,195903.600000,197044.700000,197910.300000,198848.800000,200491.400000,201370.400000,202123.900000,202474.900000
012,152939.000000,152747.071429,152395.285714,151950.571429,151415.857143,150841.857143,150336.214286,150390.000000,150694.000000,150977.071429,...,294510.142857,293405.000000,293369.214286,293681.071429,294721.571429,294987.571429,295213.785714,295030.571429,295120.500000,294198.714286
013,96047.062500,96062.375000,96053.687500,96162.562500,96255.875000,96383.750000,96424.187500,96597.875000,96839.375000,97057.625000,...,227629.062500,227389.937500,227879.562500,227693.375000,227642.812500,227726.937500,229097.312500,230553.937500,232363.375000,234215.500000
014,133912.888889,134038.166667,134142.333333,134407.500000,134567.555556,134814.722222,135018.555556,135460.444444,135866.833333,136512.944444,...,314648.277778,315445.611111,316610.166667,317781.222222,318935.666667,320379.888889,321565.277778,323152.555556,324178.166667,324879.944444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,137231.869565,137332.608696,137476.130435,137951.956522,138177.565217,138155.869565,138067.391304,138298.217391,138690.608696,138715.695652,...,316876.260870,319383.217391,322211.478261,324224.260870,326168.130435,328677.086957,331518.913043,334951.043478,337602.565217,339418.086957
991,107608.888889,107434.555556,107499.555556,107576.000000,107896.000000,108114.555556,108238.222222,108363.777778,108598.777778,109049.000000,...,267167.666667,268049.555556,268884.666667,269042.111111,269157.555556,269325.555556,270367.888889,270735.555556,270903.000000,270816.444444
992,116967.285714,116964.714286,116851.214286,116844.714286,116786.500000,116693.785714,116535.785714,116480.000000,116574.428571,116646.642857,...,265400.214286,267652.500000,270400.500000,272511.642857,274580.000000,277243.214286,280485.857143,283940.785714,286385.285714,287699.785714
993,92142.666667,92349.111111,92553.111111,92975.444444,93314.888889,93500.111111,93571.444444,93719.888889,93804.666667,94025.777778,...,269432.444444,270656.777778,271746.000000,272502.666667,273578.555556,274422.333333,275060.777778,274878.111111,274339.111111,273924.000000
995,138147.153846,138781.615385,139392.230769,140611.538462,141582.153846,142481.846154,143311.923077,143863.230769,144154.000000,144124.000000,...,325667.846154,327367.307692,329046.076923,330782.769231,332152.461538,333308.307692,332136.923077,331055.000000,328089.384615,327958.769231

In [31]:
thing

,02/01/1996,03/01/1996,04/01/1996,05/01/1996,06/01/1996,07/01/1996,08/01/1996,09/01/1996,10/01/1996,11/01/1996,...,09/01/2019,10/01/2019,11/01/2019,12/01/2019,01/01/2020,02/01/2020,03/01/2020,04/01/2020,05/01/2020,06/01/2020
ZIP_CODE_SHORT,,,,,,,,,,,,,,,,,,,,,
010,127793.954545,127611.750000,127584.431818,127463.750000,127434.318182,127415.522727,127414.659091,127539.159091,127678.409091,127719.954545,...,263877.728814,264501.271186,264883.406780,265499.576271,266206.728814,267202.644068,268609.389831,269949.305085,271476.016949,272109.118644
011,95046.700000,95106.300000,95146.100000,95125.300000,95107.100000,94946.800000,94903.200000,94733.500000,94765.600000,94719.700000,...,175186.307692,176230.923077,177502.153846,178439.076923,179127.923077,179868.615385,181280.615385,181999.461538,182735.615385,183134.846154
012,152939.000000,152747.071429,152395.285714,151950.571429,151415.857143,150841.857143,150336.214286,150390.000000,150694.000000,150977.071429,...,294008.838710,293129.709677,293018.193548,293106.548387,293682.322581,293570.741935,293157.580645,292452.354839,291899.870968,290769.677419
013,96047.062500,96062.375000,96053.687500,96162.562500,96255.875000,96383.750000,96424.187500,96597.875000,96839.375000,97057.625000,...,214547.413793,214210.620690,214521.793103,214237.758621,214183.655172,214181.689655,215297.655172,216442.724138,218178.379310,220117.000000
014,133912.888889,134038.166667,134142.333333,134407.500000,134567.555556,134814.722222,135018.555556,135460.444444,135866.833333,136512.944444,...,335756.333333,336640.809524,338022.571429,339400.000000,340829.142857,342361.238095,343589.619048,345154.666667,346132.714286,346745.904762
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,137231.869565,137156.166667,137305.041667,137780.583333,138032.875000,138025.291667,137981.250000,138230.666667,138664.583333,138703.791667,...,286576.900000,288783.433333,291212.133333,292960.800000,294623.466667,296718.633333,299156.566667,302100.533333,304502.666667,306183.733333
991,107608.888889,107434.555556,107499.555556,107576.000000,107896.000000,108114.555556,108238.222222,108363.777778,108598.777778,109049.000000,...,195801.145161,196750.580645,197584.725806,197947.693548,198411.064516,198804.967742,199459.822581,199763.419355,200099.951613,200502.548387
992,116967.285714,116964.714286,116851.214286,116844.714286,116786.500000,116693.785714,116535.785714,116480.000000,116574.428571,116646.642857,...,265400.214286,267652.500000,270400.500000,272511.642857,274580.000000,277243.214286,280485.857143,283940.785714,286385.285714,287699.785714
993,92142.666667,101987.300000,102325.900000,102829.500000,103055.090909,103305.909091,103373.454545,103499.272727,103639.181818,102729.666667,...,245081.848485,246114.151515,247080.272727,247743.424242,248779.181818,249668.212121,250074.515152,249850.393939,249199.181818,248776.515152
995,138147.153846,138781.615385,139392.230769,140611.538462,141582.153846,142481.846154,143311.923077,143863.230769,144154.000000,144124.000000,...,307373.368421,309146.736842,310896.631579,312566.842105,313949.631579,315316.789474,314871.000000,314416.631579,312464.105263,312666.315789

In [34]:
thing.melt(id_vars=['ZIP_CODE_SHORT'], 
        var_name="DATE", 
        value_name="PRICE")

KeyError: "The following 'id_vars' are not present in the DataFrame: ['ZIP_CODE_SHORT']"

In [35]:
pd.melt(thing, id_vars=['ZIP_CODE_SHORT'])

KeyError: "The following 'id_vars' are not present in the DataFrame: ['ZIP_CODE_SHORT']"

In [40]:
thing1 = thing.reset_index().melt(id_vars=['ZIP_CODE_SHORT'],var_name="MONTHLY_REPORTING_PERIOD",value_name="HOUSING_PRICE")

In [42]:
thing1.to_csv('/Users/kdugg/Documents/zillow_data_groupmelt.csv')